sudo: required
services:
  - docker

before_install:
  - docker build -t caronc2000/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true caronc2000/react-test npm test

after_success:
  - docker build -t caronc2000/multi-client ./client
  - docker build -t caronc2000/multi-nginx ./nginx
  - docker build -t caronc2000/multi-server ./server
  - docker build -t caronc2000/multi-worker ./worker
  #Log in to docker CLI - enter docker credentials as env variables in travis
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take these images and push to docker hub
  - docker push caronc2000/multi-client
  - docker push caronc2000/multi-nginx
  - docker push caronc2000/multi-server
  - docker push caronc2000/multi-worker
